### ISSUE TITLE
SendCode shortcut does not send code 

### ISSUE THREAD

**Issue by albertostefanelli** [randy3k/SendCode#100]
This happens with Sublime Text 3 (Build 3176) with Terminal (mac default), Terminus, TerminalView, R-Studio, R-Gui. If i use the send code option in the R-IDE package it works. Changing key binding does not resolve the problem.

Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

**Comment by randy3k** [comment]
There is not enough information for me to determine the cause. Please make the report reproducible.

**Comment by albertostefanelli** [comment]
The problem is that by default both combinations of shortcuts that I used were already assigned. I am sorry for this. However, making a note in the instruction could be useful.
