### ISSUE TITLE
SyntaxError: multiple statements found while compiling a single statement

### ISSUE THREAD

**Issue by maniacalwhistle** [randy3k/SendCode#102]
I am not super fluent in Python or the ins-and-outs of Sublime Text packages and I am having a hard time trying to use a combination of SendCode and Terminus to run some Python code.

The first thing to note is that the code runs fine with a simple cmd+b build (aka results show up fine in Sublime native console with Python build).

When I run with SendCode however I keep getting an error that reads, "SyntaxError: multiple statements found while com piling a single statement". I've tried a couple of things to rule out issues and see what is going on:
1. I used a linter (Anaconda) to make sure the indentation and formatting was good.
2. I ran simple code through SendCode to make sure it worked (aka one line saying 'a = 5')
3. I sourced the file in a regular terminal window (python _filename_) and it produces the results.
4. I read through some of the older issues here about bracketed_passte_mode and tried adjusting the settings (from 'true' to 'false') but still can't get it to work.

I even tried to make a really simple multiline script to see if I could get it to work but still sometimes got the multiple statements issue if I highlighted the code block I intended to send (instead of hitting cmd enter one by one).

Anyway, I've tried a lot of things but can't seem to get it to work on my own. So I am looking for some help. Both packages seem really cool and I'd really like to use them.

<img width="1053" alt="syntax_error_multiple_statements" src="https://user-images.githubusercontent.com/25876624/45468284-da430900-b6f1-11e8-8156-9ea20cec1805.png">

<img width="1057" alt="toy_example_with_same_error" src="https://user-images.githubusercontent.com/25876624/45468294-ddd69000-b6f1-11e8-83f0-09dce682af89.png">

[think_complexity.txt](https://github.com/randy3k/SendCode/files/2377766/think_complexity.txt)

**Comment by randy3k** [comment]
You should use IPython instead of python.

**Comment by maniacalwhistle** [comment]
Wow. That was easy. Thanks.
