### ISSUE TITLE
Julia file with `t` word

### ISSUE THREAD

**Issue by pochoi** [randy3k/SendCode#106]
```julia
println("before")

typeof(1)

println("after")
```

Weird thing happens in a .jl file like the above.
When my cursor is at the line of `typeof(1)` and I press CMD+enter, I expect to send the `typeof(1)` only.
However, all the line before `typeof(1)` (non-inclusive) is sent to terminal.

I remember it also happens with some other `t` starting words, but I don't remember which words exactly.

Not sure whether it is just my macbook problem. Can you reproduce it in your macbook?
I am using OSX 10.10.5 with iTerm2 3.2.0beta5

**Comment by randy3k** [comment]
Could you check it again.

**Comment by pochoi** [comment]
Great! I can send `typeof(1)` now! Thanks so much!

**Comment by pochoi** [comment]
Nope... Things go worse...

```julia
println("before")

for k in 1:10
    println(k)
end

println("after")
```

If the cursor is at `for k in 1:10` and I press CMD+enter,
`println("before")` is sent to the terminal.

**Comment by braydenware** [comment]
I have this issue with julia files as well, but it is only in the most recently tagged version v0.4.11. Trying to send blocks of code sends lines from above the block of code. I manually installed v0.4.10 to check, and that version works fine.

**Comment by randy3k** [comment]
@braydenware 
I should have fixed it in v0.4.13

**Comment by pochoi** [comment]
Thanks so much! It works fine now. And sorry for introducing this bug in my commit :pensive:

**Comment by randy3k** [comment]
I was me who introduced the bug.
