### ISSUE TITLE
sending code to R suddenly stopped working yesterday

### ISSUE THREAD

**Issue by emilBeBri** [randy3k/SendCode#114]
Hi,

The combination of Sublime Text 3 and a tmux session has been working smoothly for a long time - yesterday though, suddenly sending code to tmux starting malfunctioning. I can ctrl+ENTER, but either:

1) the command is not send to tmux (most frequent)
2) the command is sent, but with a very long delay (more than 10 seconds)

I have not changed anything on my computer, so it must be an update error?

Running Lubuntu 18.10 with R 3.5.1.

**Comment by randy3k** [comment]
There is also no update recently, not sure the cause.

**Comment by emilBeBri** [comment]
Strange. When I try to switch to Rstudio or terminus, it's the same.

**Comment by emilBeBri** [comment]
Could it be the rlanguageserver instead? or the R-IDE?

**Comment by randy3k** [comment]
They should not cause any delays in SendCode. I assume that you have tried restarting the editor or your computer.

**Comment by randy3k** [comment]
One possibility is that one of your packages is blocking the worker thread frequently.

**Comment by emilBeBri** [comment]
Oh damn do I feel foolish, I installed the package "color gutter" yesterday that displays color of HEX-values in the gutter. Removing that removed the problem. Sorry for the inconvience.

**Comment by randy3k** [comment]
Awesome.
