### ISSUE TITLE
Sending sometimes stops early when sending code to a tmux session with radian running in the session

### ISSUE THREAD

**Issue by ChHaeni** [randy3k/SendCode#116]
Today I decided to switch from the 'normal R terminal' running in tmux to Randy's radian. I'm (once again) very pleased with Randy's creation. I think radian is a wonderful R console that enables some powerful features. One issue that I have (& I assume this is related to sendcode) is, when I send code to a tmux session, normally everything works fine, however if I have a radian session running in tmux, sometimes not all of the selected code will be sent and sending sometimes stops in the middle of a (small) block, say a function or if statement or similar...

**Comment by randy3k** [comment]
Try turning on the bracketed paste mode if you are using radian. It will help sending a block of code.

**Comment by ChHaeni** [comment]
Yep, seems to solve the problem. Thank you.

**Comment by randy3k** [comment]
You might need to turn it off for the original R console.
