### ISSUE TITLE
option to specify decorator

### ISSUE THREAD

**Issue by apoorvalal** [randy3k/SendCode#117]
Could the choice of decorator `#+` or `# %%` for code cells / cursor expansion be set by syntax in the user settings file? 

I currently have a single shortcut to insert `# %%` across julia/python/r files (since I use Hydrogen for atom on a different machine and it expects the `# %%` syntax regardless of language). Sendcode doesn't recognise this decorator (`# %%`) and I'd like to set it up so it does.

Thanks for the great package!

**Comment by randy3k** [comment]
Well, it makes sense. Actually, it may worth the effort to refactor the code for python/r/julia to do expansions. The code is not recycled and resued in the current implementation.

**Comment by apoorvalal** [comment]
That was quick. Thanks a lot!

**Comment by apoorvalal** [comment]
will there be a release implementing the changes you committed? I can't seem to find it on package control.

**Comment by randy3k** [comment]
I’ll make a release soon when I have some free time. Meanwhile, please free to clone the repo to your `Packages` folder.

**Comment by apoorvalal** [comment]
got it. Thanks!
