### ISSUE TITLE
Window Focus changed after sendcode

### ISSUE THREAD

**Issue by albert-ying** [randy3k/SendCode#127]
Hi, I want to send the code line by line on sl3 on OS by keep pressing cmd+return (like what we did in Rstudio). I opened two sublime windows, one for the script, another for REPR[r]. However, after I pressed cmd+return for one line in the script, the focus changed to the REPR[r] and I have to manually change the focus back to script to send the next line.

How can I keep the focus on the script window when sending the code?

**Comment by randy3k** [comment]
What program are you sending the code to? SublimeREPL? If that is the case, you could switch to Terminus. SublimeREPL has not been maintained for some time already.

**Comment by albert-ying** [comment]
Thank you, it works now.
