### ISSUE TITLE
can't send code to RStudio

### ISSUE THREAD

**Issue by eteitelbaum** [randy3k/SendCode#129]
Hi Randy,

I have used R-IDE and SendCode to write and knit R Markdown files on my PC running Windows 10 , but now I can't get it to work. Not sure if it is an R-IDE issue or a SendCode issue or what.  I tried reinstalling both packages and have selected RStudio Desktop in the command palette as the program for SendCode. I am trying to use ctrl + b to knit the file. I have tried knitting a number of files that have worked in the recent past. I am not a programmer so I am hoping it is not something really dumb. Here is the error code I get in the console:  

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 884, in setup_
    items = self.list_items()
  File "C:\Users\emman\AppData\Roaming\Sublime Text 3\Packages\R-IDE\ride\buildsys\exec.py", line 80, in list_items
    "cat(.packages(all.available = TRUE), sep='\n')").strip().split("\n")
  File "C:\Users\emman\AppData\Roaming\Sublime Text 3\Packages\R-IDE\ride\r.py", line 53, in R
    "Failed to execute RScript with the following output:\n\n{}".format(stderr))
Exception: Failed to execute RScript with the following output:

Error: unexpected end of input
Execution halted

Thanks! 

--Manny T

**Comment by randy3k** [comment]
What happened if you run `cat(.packages(all.available = TRUE), sep='\n')` in R?

**Comment by eteitelbaum** [comment]
You mean in RStudio? I get a list of packages. Is there one in particular that I am looking for? languageserver is there...

**Comment by randy3k** [comment]
O, I guess I figured out the reason. By the way, the bug is not related to SendCode but R-IDE. You should have no issue in sending code.

**Comment by eteitelbaum** [comment]
OK so I reinstalled R-IDE and still can't get Sublime Text to send the code to RStudio. Now, if I hit ctrl+b I just get the R-IDE: Exec field (but no error in the console). 

I am still able to edit my code using R-IDE in Sublime, save it and then knit it in RStudio. I just can't send it directly from Sublime to RStudio.  

Also, I am not sure whether this matters, but in the R-IDE dropdown, only Exec is available to select. All of the other options, including "Render R Markdown" and "Knit Rnw" are greyed out. I seem to remember these being available earlier, although I always used the keyboard shortcuts and not the drop down menu to send the code to RStudio. 

Thanks for your help.

**Comment by randy3k** [comment]
Did you apply R Markdown syntax to the file?

**Comment by eteitelbaum** [comment]
Thanks, Randy. Yes the file is RMarkdown syntax. When I hit `ctrl+shift+b` I get a field that opens up at the top which says R-IDE: Exec and then if I click in that nothing happens. 

I had it working fine and sending code directly before. I am not sure what changed. Maybe I just need to reinstall everything. For now, I suppose I can just use R-IDE in Sublime to edit the markdown file, save it and then knit it in RStudio.

**Comment by eteitelbaum** [comment]
Just to follow up on this, it seems the issue was related to the improper configuration of `R_LIBS_USER` that we discussed elsewhere: 

[https://github.com/REditorSupport/sublime-ide-r/issues/42](url)

[https://github.com/REditorSupport/languageserver/issues/262](url)

Thanks again for your help.
