### ISSUE TITLE
SendCode no longer sends code to different active tmux sessions

### ISSUE THREAD

**Issue by ChHaeni** [randy3k/SendCode#131]
I have many sublime projects open on different virtual desktops sending code to different tmux sessions. Up to recently, sendcode always used to send code to the active tmux session, but now it insists on sending code to the first tmux session that I used to send code to...
Is this intended or is it a bug? If this is a bug, could you please tell me what you need to know from my system and setup? :-)
(running debian 10)

**Comment by randy3k** [comment]
We use `tmux set-buffer` and `tmux paste-buffer -d` to send code. I have no idea how the session is selected though.

**Comment by ChHaeni** [comment]
Thx, I think that was it! I recently added a binding to copy from tmux to system buffer. Removing that binding in tmux conf seems to fix this issue.

**Comment by ChHaeni** [comment]
@adomingues I'm no longer using sublime, but the line in my tmux.config that caused the issue was the following 'copy to system clipboard binding':
```
# copy to system clipboard (https://github.com/tmux/tmux/issues/599)
bind -Tcopy-mode-vi M-y send -X copy-pipe "xclip -i -sel p -f | xclip -i -sel c" \; display-message "copied to system clipboard"
```
After removing this binding, everything worked fine again.
Hope that helps!

**Comment by adomingues** [comment]
Cheers @ChHaeni. In the meantime I figured that setting the program to "linux-terminal" instead of "tmux" was a better solution - it send the code to the session terminal in the active worskpace (Ubuntu).
