### ISSUE TITLE
00~ and 01~ are added to every line of text being sent to iTerm

### ISSUE THREAD

**Issue by eddataminr** [randy3k/SendCode#138]
I have the file type set to SQL and when I send code to a SQL terminal it sends fine, but if I try to send it to a regular terminal it adds "00~" to the beginning and "01~" to the end of the sent text

**Comment by randy3k** [comment]
It looks like you have enabled brackets paste mode but the SQL program does not support it.

**Comment by eddataminr** [comment]
ah that worked, thank you!
