### ISSUE TITLE
Safari-Jupyter send does not work anymore 

### ISSUE THREAD

**Issue by miguelroboso** [randy3k/SendCode#16]
What is the fastest way for me to troubleshoot the issue? 
It works correctly when I use Chrome-Jupyter, but with Safari no luck
ST 3 on Mac Os X (El Capitan)

**Comment by randy3k** [comment]
Most likely you haven't enabled JavaScript for AppleScript. It is a new security measure introduced on El Capitan.

Check the option "Enable Allow JavaScript from Apple Events" in the Develop menu.

**Comment by anasrana** [comment]
Maybe worth putting in the Readme file. I had this issue and couldn't figure out why it wouldn't work.

**Comment by randy3k** [comment]
README updated.
