### ISSUE TITLE
sent commands are not in Repl R history

### ISSUE THREAD

**Issue by fabeit** [randy3k/SendCode#18]
Hello, really strange, when I use SendREPL to send R code to REPL r, the commands I send with ctrl+enter execute but do not show up in the command history, if I use arrow-up I only see the commands I typed or copy and pasted.

**Comment by randy3k** [comment]
Are you using SublimeREPL?

**Comment by fabeit** [comment]
yes

**Comment by randy3k** [comment]
This is not caused by SendREPL, please contact SublimeREPL.
