### ISSUE TITLE
Terminal on Linux

### ISSUE THREAD

**Issue by Auerilas** [randy3k/SendCode#21]
Are there any plans to be able to send to a regular Terminal on Linux, or is this not possible because of the number of different distributions/terminal emulators packaged by every distro?

**Comment by randy3k** [comment]
You are very correct. Additionally, not all emulators support sending text, I have spent some time playing with gnome-terminal of Ubuntu, but I only found a hacky way to accomplish this.

**Comment by fangly** [comment]
In case that helps, I believe many distros (e.g. Debian, Ubuntu) define an "x-terminal-emulator" alias that you can use (https://www.howtogeek.com/howto/ubuntu/set-the-default-terminal-emulator-on-ubuntu-linux/).

**Comment by randy3k** [comment]
`x-terminal-emulator` can be only used to open the REPL and it could not be used for sending text.

**Comment by randy3k** [comment]
gnome-terminal is supported at latest master branch.

**Comment by randy3k** [comment]
If you request a particular terminal and distribution, please open a specific issue.

**Comment by mreca89** [comment]
I'm having trouble using SendCode with gnome-terminal (using Ubuntu 17.04). After installing in sublime's package control and using `ctrl+shift+p` to do `SendCode: Choose Program` and select `linux-terminal`, code I type fails to send to my terminal.

Closing out sublime and my terminal after doing the above and reopening both, but I still get nothing on `ctrl+enter`. I haven't modified the SendCode settings file - it just reads `{"prog": "linux-terminal"}`. The companion `SendCode (Linux).sublime-settings` file is also unmodified and has the pertinent line: `"linux_terminal": "gnome-terminal"`

Am I doing something incorrectly or is this a genuine bug?

**Comment by randy3k** [comment]
You may need to run `xprop | grep WM_CLASS` and click the active terminal to identify the terminal class which may not be `gnome-terminal`.

**Comment by mreca89** [comment]
Thank you for the speedy response! Unfortunately, this did not work for me. Upon running those instructions (and my apologies for missing it in the comments of the settings file), I receive as output: `WM_CLASS(STRING) = "gnome-terminal-server", "Gnome-terminal"`. I tried placing `gnome-terminal-server` as the value for the `linux-terminal` key in the settings file, saving, restarting both sublime and terminal, and still no luck using SendCode. I did the same for `Gnome-terminal` afterwards.

**Comment by mreca89** [comment]
Any other suggestions?

**Comment by randy3k** [comment]
What code are you using SendCode with? python or something else?

**Comment by mreca89** [comment]
Python, yes (though I

**Comment by randy3k** [comment]
SendCode keymappings are enabled by default for `source` scoped files. Open the terminal and a python file in Sublime. Then write something and hit `C+Enter`. The code should be sent to the terminal. Otherwise, report what you observe at the Sublime Console (if it is not working).

**Comment by mreca89** [comment]
Apologies for the long delay, but this works. Also, `ctrl(cmd)+shift+p` -> `set syntax: <language of choice>` does the trick too (for anyone else who might've been having trouble)
