### ISSUE TITLE
Document the obvious: REPL must be already open

### ISSUE THREAD

**Issue by fangly** [randy3k/SendCode#27]
I have installed SendREPL today and got frustrated because it would not send a simple piece of R code `1 + 1` to an R terminal (nothing happened). Fortunately, I stubled upon a clip on Youtube that demonstrated that the R console needs to be open before SendREPL can send to it.

So, please state in the documentation: the REPL must already be opened before one can send to it. That is surely obvious to you, but not to a newcomer. Additionally, perhaps you could issue a nice error message if the REPL is not reachable?

Cheers,
Florent

**Comment by randy3k** [comment]
I believe that there is some kind of error messages in Sublime Console in such cases. A better message should be thrown though.

**Comment by randy3k** [comment]
README updated.
