### ISSUE TITLE
Trying to change the default key binding

### ISSUE THREAD

**Issue by SCP-028** [randy3k/SendCode#30]
Hi, I'm trying to change the default key binding of `send current line/selection` from `ctrl+enter` to `alt+enter` in the package `R-box`. Could you please offer an example? I tried the following but it didn't work. Thanks!
```
"keys": ["alt+enter"], "command": "send_repl",
"args": {"prog": "rstudio"},
"context": [
    {
        "key": "selector",
        "operator": "equal",
        "operand": "source.r"
    }
]
```

**Comment by randy3k** [comment]
It looks right.
```js
{
    "keys": ["super+shift+e"], "command": "send_repl",
    "args": {"prog": "rstudio"},
    "context": [
        { "key": "selector", "operator": "equal", "operand": "source.r" }
    ]
}
```

**Comment by SCP-028** [comment]
@randy3k After adding this to settings, nothing happens in RStudio when I press `alt+enter`. Do I need to modify anything else?

**Comment by randy3k** [comment]
Did you put the keybind in the correct file? You should put it in the file `Default (xxx).sublime-keymap` (`xxx` = your platform).

**Comment by SCP-028** [comment]
@randy3k Got it. Thanks!
