### ISSUE TITLE
Windows 10: Rterm is running, but nothing happens and there is no error in the console.

### ISSUE THREAD

**Issue by mvacha** [randy3k/SendCode#31]
Hi, I cannot get this plugin to work for me. I have Rterm running, SendCode default repl is set to R, but when I press ctrl+enter, nothing happens and there is no error in the console :(

**Comment by randy3k** [comment]
It sends to the R GUI if `R` is chosen. 
![screen shot 2017-04-03 at 3 01 44 pm](https://cloud.githubusercontent.com/assets/1690993/24626300/d1e8698e-187e-11e7-8d98-bbedc04793bd.png)

Alternatively, you could use Cmder or ConEmu and run Rterm on top of it.
![screen shot 2017-04-03 at 3 04 14 pm](https://cloud.githubusercontent.com/assets/1690993/24626304/d4b63d4e-187e-11e7-927f-f88f70b43311.png)

**Comment by mvacha** [comment]
Ok, thanks! So it's not possible to just run R in cmd/powershell and send code into the Rterm running there?
Could you please add this to the readme? I'm sure I'm not the only person to fall for this.

**Comment by randy3k** [comment]
I believe that with some efforts, one can make it possible to send code to powershell. But why not just use Cmder when it performs much better than the others?

**Comment by mvacha** [comment]
Yep, cmder is fine, I was just curious :)
