### ISSUE TITLE
code sent appends `01~`, breaking last line in REPL

### ISSUE THREAD

**Issue by bitworm** [randy3k/SendCode#33]
On osx, sublime text 3, iterm/terminal, python 2:

sending a cell of code appends the string `01~` at the end, preventing last line of code from running.  This appears to be coming from line 30 of iterm_bracketed.applescript.  Removing `01~` works, I don't know what else it breaks...

**Comment by randy3k** [comment]
Check: https://github.com/randy3k/SendCode#troubleshooting

You shouldn't use the python shell. You should use either iPython 5.0 or pypython which supports bracketed paste mode.

**Comment by bitworm** [comment]
This is correct.  Updating ipython fixed the issue.
