### ISSUE TITLE
sendcode doesn't send code to Rgui

### ISSUE THREAD

**Issue by fabeit** [randy3k/SendCode#34]
I have r extendend and sendcode packages installed, I selected R in the send code, I press ctrl+enter but it doesn't send the code to the r console.

I tried to restart sublime and I checked the user options in the sendcode package, everything seems fine. I am suing the R console (64bit)

**Comment by randy3k** [comment]
Is the R console open when you are sending the code? Is there any error messages in the sublime console?

**Comment by fabeit** [comment]
Yes the R console is open, ctrl+enter goes to the next line, console output 
File "C:\Users\Sir Punk\AppData\Roaming\Sublime Text 3\Packages\SendCode\src\r\__init__.py", line 45, in send_to_r
    win32api.PostMessage(rid, win32con.WM_SETFOCUS, pasteid, 0)
pywintypes.error: (5, 'PostMessage', 'Access is denied.')

**Comment by fabeit** [comment]
Ok solved the problem! I had to run Sublime As administrator! Is there a way around this?

**Comment by fabeit** [comment]
So it seems sendcode doesn't like sending plot() after par(), why? Graphics can be open and send correctly other lines of code.

**Comment by randy3k** [comment]
SemdCode doesn't interact with the r console (it doesn't know anything about the console). I have no idea why plot() is not sent.

**Comment by fabeit** [comment]
So it's not about plot() or any other function. When R Graphics window is open the commands don't reach the console

**Comment by randy3k** [comment]
I see what you mean now. Currently, It is no way to send code to the R Console if the R Graphics window is on top of the R Console. You will need to click on the R Console if it happens.

**Comment by randy3k** [comment]
There is actually a solution. Use `win32gui.EnumChildWindows` to iterate over all the child windows and bring up the matching child window by `win32gui.BringWindowToTop`.

**Comment by randy3k** [comment]
Should be fixed at master.

**Comment by fabeit** [comment]
ok yes! I can now reproduce and fix the issue by clicking on the R Console. And updating the package fixes the issue! Thanks!
