### ISSUE TITLE
how to install SendCode in Sublime 3?

### ISSUE THREAD

**Issue by JeromeMathieuEcology** [randy3k/SendCode#35]
Hi,
Sorry for this newbie question, but how can I install SendCode in Sublime 3 under windows 10?

I tried with the Package Control but SendCode is not in the list. 

![image](https://cloud.githubusercontent.com/assets/12587730/25092285/4d4a9458-238d-11e7-9818-c9993f9fcec3.png)

Then I tried to add the github repository, but I still can't find it.

> 
    {
	 "bootstrapped": true,
	 "in_process_packages":
	 [
	 ],
	 "installed_packages":
	 [
	 	"Package Control",
	 	"SublimeREPL"
	 ],
	 "repositories":
	 [
	 	"https://github.com/randy3k",
	 	"https://github.com/randy3k/SendCode",
	 	"https://github.com/randy3k/SendCode/tree/master/src/r"
	 ]
    }
>

Thank you in advance for you help!
Jerome

**Comment by randy3k** [comment]
It could be installed using Package Control as usual. Maybe Package Control is caching the most recent update which was released a few minutes ago??

**Comment by JeromeMathieuEcology** [comment]
Thanks for your help.

I managed to install from the 
>Tools\Command Palette\ Package Control: Install Package.

However I don't succeed to send code to R (Gui or any other).

if I try
> SendCode : ChooseREPL program

then R does not appear in the list

![image](https://cloud.githubusercontent.com/assets/12587730/25093395/70309198-2392-11e7-8c37-544aebefec33.png)

if I do first

> sublimeREPL: R

Then I have a new tab in sublime with R running. If I stay on this tab and try again 

> SendCode : ChooseREPL program

I (sometimes, not always) have R GUI in the list .

![image](https://cloud.githubusercontent.com/assets/12587730/25093471/b528dca6-2392-11e7-8ba8-55d71e7abd46.png)

(if I switch to another tab than the R one in sublime,  R GUI does not appear any more in the list.)

Even when I selected RGUI, and that an RGUI session is already open, I don't succeed to send code to R (or to the R tab in Sublime).
To send code I select the text and hit ctrl+enter like in "Usage" section on 

https://github.com/randy3k/SendCode

**Comment by randy3k** [comment]
You need to open an R file so that the options for R will be displayed and the SendCode functionality will work. So, did you open a R script file at all?

**Comment by JeromeMathieuEcology** [comment]
That's it !!!!

If I save my script with .R extension it does work!

Thanks a lot!
Jerome

**Comment by nwwangnan** [comment]
Dear all:
I would like to ask a dumb question. I am using mac. I am trying to use sendcode pulg-in to send code to R and Python. It works well with Python. But when I was trying to send R code to Terminus (right panel), It always start a new R console out of sublime instead of the R console that I called from terminals. What should I do to make sure I can send code to the R console in sublime?

**Comment by randy3k** [comment]
Would you explain what you meant when you said "a new R console out of sublime"? Is it the R GUI.app, Terminal.app or a new Terminus window in sublime?
