### ISSUE TITLE
Not executing multi-line statements in the IPython debugger

### ISSUE THREAD

**Issue by felipeespic** [randy3k/SendCode#39]
Hello, 

If I send multi-line statements to ipdb, it does not execute them. Although, they are pasted into the shell with no errors/warns.

Also, if I set bracketed_paste_mode as true,  it throws:
`%cpaste -q`
`*** SyntaxError: invalid syntax (<stdin>, line 1)`

IPython: 5.3.0
ipdb: 0.10.3

Thanks,
Felipe

**Comment by randy3k** [comment]
How did you run `ipdb` in `iPython`?

If you are using iPython 5, you should have `bracketed_paste_mode` as `true`.

**Comment by felipeespic** [comment]
I just insert this line:
`if True: import ipdb; ipdb.set_trace(context=8)`

**Comment by randy3k** [comment]
I have no problem to send a single line to ipdb in this way, what OS you are using?

**Comment by felipeespic** [comment]
Me neither, the problem is when sending multi-line. I am using Ubuntu 16.04LTS

**Comment by randy3k** [comment]
I assume `tmux` is used and I also don't have any problem with multi-line code.

![screen shot 2017-05-12 at 4 10 17 pm](https://cloud.githubusercontent.com/assets/1690993/26015120/89dd7f80-372d-11e7-8c91-863093311fb3.png)

**Comment by felipeespic** [comment]
Did you check that the code is actually executed, and not only pasted? For example, if you run:

`ga=2`
`gu=4`
`ge=3`

Then, could you access the values of these variables?

**Comment by felipeespic** [comment]
In my case:

![screenshot-20170512212334-372x136](https://cloud.githubusercontent.com/assets/16511990/26015537/53b83b3a-3759-11e7-80f7-8ba624172060.png)

**Comment by randy3k** [comment]
You cannot just print `ga` by typing. You need to do `p ga`

**Comment by randy3k** [comment]
I reckon that `ipdb` doesnot support multple lines.

![screen shot 2017-05-12 at 4 35 14 pm](https://cloud.githubusercontent.com/assets/1690993/26015951/07ceda4e-3731-11e7-989f-1833da122967.png)

**Comment by felipeespic** [comment]
If that is the case, it wouldn't be possible for SendCode to fake the multi-line execution by sending the selected lines one by one?

**Comment by randy3k** [comment]
The issue is SendCode doesn't know which command line is running in the terminal. Plus, there is a time-syncing issue if the selected line is sent one by one.

**Comment by felipeespic** [comment]
I think that if there were a variable in SendCode to set the "fake multi-line" on, theoretically that should work for any Python interpreter (including debuggers), since all are able to receive one line at a time. So, people could select between the normal and the "fake" multi-line. Also, I guess what you mean with the time-syncing, and yes, that could be very difficult to address.

Anyway, I think it would be great if there were a workaround for this problem.

**Comment by randy3k** [comment]
Python is a weird language which is indentation sensitive. That are situations in which a block cannot be sent line by line. For instance, your "fake multi-line" mode will probably fail to send
```
def f():
    # some black new lines


    return True
```

I believe the use case of sending a regular code block to the interpreter is far more important than sending a code block to debuggers.

**Comment by felipeespic** [comment]
Yes, I think you are right. Thank you
