### ISSUE TITLE
SendCode and R-Box both send lines to R?

### ISSUE THREAD

**Issue by rrodrigueznt** [randy3k/SendCode#40]
Hi! New to Sublime Text, new to SendCode and R-Box, new to GitHub: please, accept my apologies in advance if this is not the right channel, or the questions are too simple! Thanks for any insight!

I'm also a happy user of Sublime Text as R code editor, but I'm having a hard time to make it coherently work on several platforms. As I'm close to understanding how this combination works on Mac OS X, I'm facing some issues in several PCs running different Windows flavours.

Please, allow me to ask some very simple question to further elaborate on that issues. Could you tell me if these three sentences are correct?

1) Both SendCode and R-Box can be used to send R code from Sublime Text to R (terminal, R-GUI or RStudio).
2) SendCode can also be used to send code to other programmes.
3) R-Box has some nice extra features as R autocompletion and pop-up hints.

Please, am I right?

Thanks for your time!

**Comment by randy3k** [comment]
1) R-Box does have the "send code" feature. You would need to install both.

2) Yes. It also supports Julia and Python languages.

3) Yes

**Comment by rrodrigueznt** [comment]
Thanks, Randy.

Still about 1) Should I read R-bix hasn't the send code feature, thus I should install both, R-box and SendCode to get it? Does R-box relies on SendCode for the sending code feature? 

Sorry for insisting, but it is not clear for me yet!

**Comment by randy3k** [comment]
You are right, typo updated. 😅

**Comment by rrodrigueznt** [comment]
Thanks, Randy!
