### ISSUE TITLE
SendCode: Choose RPL Program

### ISSUE THREAD

**Issue by rrodrigueznt** [randy3k/SendCode#41]
Hi! Thanks, Randy, for answers in #40! Once #40 was worked out, a couple of issues with SendCode configuration,

I've installed it in several Sublime Text 3, Stable Channel, Build 3126 instances running on Mac OS X, Windows 10 and Windows 7. I am not sure about the following statement...

"To configure SendCode, launch Tools > Command Palette, enter SendCode: Choose RPL Program and choose your option. To start using it, open the program you have selected, and start sending code lines or code chunks by selecting them and hitting Control+Enter"

As far as I can see here, this sentence applies at least to Mac OS X and Windows 10 installations, where I can see a complete list of options when entering SendCode: Choose RPL Program as you can see here...

![2017-06-04](https://cloud.githubusercontent.com/assets/1550835/26763660/a642253c-4956-11e7-8738-91d8aa43fc68.png)

But Windows 7 doesn't show R GUI and RStudio Desktop options. Thus, I must instruct other users to change SendCode preferences by hand. It is not a hard work, but it adds an extra layer of complexity to persons that have never use this software.

**Please, is this a Windows 7 related issue? Must I be able to see all the options also in Windows 7? If yes, how SendCode does detect available software? Should I instal R, R GUI or RStudio Desktop in a specific way?**

My preference is to work with portable releases as I can't be sure of having administrative rights on the working boxes.

Thanks in advance for your time: I'm not able yet to dig into Python code to discover this wonderful package does work!

**Comment by randy3k** [comment]
The R GUI and RStudio options are shown only for R files, so you need first make sure the opened file is a R script file.

**Comment by rrodrigueznt** [comment]
Ok, thanks! I've just confirmed this behaviour in the box running Windows 10 I'm using right now. This behaviour means that I have to open a file and associated it with R Syntax before configuring SendCode. And that before sending code chunks to R GUI or RStudio I've to be sure that a given script file is associated with R syntax.

Given that currently SendCode is configured on a _per-installation_ basis and it is not possible to send code to different programs based on their syntax, would be easier to show all supported options just after installing SendCode without needing to opening and associating a script file with a syntax?

Thanks!

**Comment by randy3k** [comment]
The command palette command is meant to set the global settings. If you want to specify different programs for different syntax, you would need to edit the the sublime-settings files. Check Preferences -> Package Settings -> SendCode -> Settings.

**Comment by rrodrigueznt** [comment]
Ok! I think I understand now the whole scene! Thanks for your time!

Only one tip: at least in my **Windows 10** installation, the cursor must be in RStudio console before being able to send code to it. Both Windows 7 and Mac OS X receive code wherever the cursor is provided the program is running!

**Comment by rrodrigueznt** [comment]
I must correct my previous post and I prefer to add a new one to keep the track: Windows 7 behaves similarly to Windows 10: cursor must be on RStudio console before sending the code. Sorry for the noise!

**Comment by randy3k** [comment]
This issue has been a while, so I am going to close it. If you still face the same issue, feel free to re-open it or open a new issue.

**Comment by rrodrigueznt** [comment]
After some time out of this track, I would like to go back to it. Please, is it possible to configure SendCode to submit code to RStudio even although cursor is not in RStudio's Console when pressing Ctrl+Enter? Thanks!
