### ISSUE TITLE
Nothing happens - Cmder Windows 10

### ISSUE THREAD

**Issue by gvashishtha** [randy3k/SendCode#42]
I installed SendCode using Package Control in Sublime Text 3, but when I highlight text and press CTRL + ENTER, nothing happens.

**Comment by randy3k** [comment]
Could you try providing the path to ConEmuC.exe in SendCode settings?

**Comment by randy3k** [comment]
Oops, closed by accident.

**Comment by gvashishtha** [comment]
That fixed it! Sorry for the basic question and thank you!

**Comment by randy3k** [comment]
No problem at all.
