### ISSUE TITLE
Keybind for sending all the file to the REPL

### ISSUE THREAD

**Issue by GhostValk** [randy3k/SendCode#44]
Hi!

What is the command/args for keybinding to send all the file content to the REPL and not only the selected line?

Cmd+b is NOT working for me, and there isn't even a binding for it in SendCode default bindings.

Thanks in advance!

**Comment by randy3k** [comment]
There is no such functionality shipped with SendCode. You could write your own `sublime_plugin.TextComand` and invoke the SencCode command by

```python
view.run_command("send_repl", {"cmd": "<content>"})
```

**Comment by GhostValk** [comment]
Well, bypassed it just setting an argument to the keyybind that sources the file:

"args": {"cmd": "setwd(\"$file_path\")"}

Wasn't exactly what i was hoping for, but it basically fulfills 99% of what i dneeded =) Thanks!


I have another question... I'm piping the code to tmux under OSX, it works fine, but when i have a multipane session, the code is piped to the active panel, it's possible to pipe the code to an specific window of tmux?

**Comment by randy3k** [comment]
I am not aware of such possibility. Please let me know if you know to do it.

**Comment by GhostValk** [comment]
Well, i'm nto sure at the moment, but i think it depends on the call you use to send keys to tmux,

The python function send_to_tmux is standard python api or you made it?

**Comment by randy3k** [comment]
It is a function in `src/tmux/__init__.py`

**Comment by GhostValk** [comment]
Yah.. found it already; i'm trying to make a call to select a fixed tmux-panel (2 in my case) inside the send_to_tmux function:

`subprocess.check_call([tmux, 'select-pane -t 2'])`

But it's not working =/

**Comment by GhostValk** [comment]
Looks liek the call is even easier, as paste-buffer and set-buffer could also use -t flag

**Comment by randy3k** [comment]
But how can we let the user to choose which pane to use? It will be cumbersome to ask every time.

**Comment by GhostValk** [comment]
Yeah, good point.. I don't know how the scripts interact with the options set (i've never made a plugin), bu i'll try tomorrow to make a function that parses which tmux panel has the R prompt open and select it automatically.

**Comment by randy3k** [comment]
The original issue was resolved, feel free to open another thread for the tmux pane issue.
