### ISSUE TITLE
Problem in Windows (cmder / ConEmu)

### ISSUE THREAD

**Issue by Cortajarena** [randy3k/SendCode#45]
Hi, Randy. First of all, thanks a lot for the package, I've been using it on Linux and MacOSX for a while now and it works like a charm!

I just installed it in Windows 10 today and I have tried with Cmder and ConEmu and can't seem to get the code sent to neither of them. 

I have been reading your code too. I am not sure, but may the issue be related to the names of the processes in windows? I have checked that you get the process names using "re" but on my machine the process name is, for instance, "ConEmu console extender (x64)" for cmder, when I was expecting it to be called something like cmder.exe. 

Once again thanks a lot for the package!

Inigo

**Comment by randy3k** [comment]
On windows, you will need to specify the path to ConEmuC.exe in the environmental variable PATH.

**Comment by Cortajarena** [comment]
Uhhhh shit right..! Thanks again and sorry for that! Working perfectly now! Great job!
Inigo

**Comment by jayhjim88** [comment]
I have the same problem. I don't understand what @randy3k 's comment means by set the environment variable PATH. Where do you and how do you do that?

**Comment by randy3k** [comment]
It may be easier to specify the PATH to ConEmuC.exe in SendCode settings.

**Comment by jayhjim88** [comment]
Thanks for reply @randy3k. I tried that already along with many other solutions from googleing a lot. This one does not do anything. I spent about a week (10min to hour each day ish) to resolve this issue of shortcut but I am frustrated and want to give up. I just manually copy code on Repl now... Too newb so please walk through with me here. This is what I put in windows Sendcode setting file.
**"cmder": "C:\\Users\\''some personal path name here''\\cmder\\vendor\\conemu-maximus5\\ConEmuC.exe"**

**Comment by randy3k** [comment]
You need to escape backslashes in a string, and the option is called `conemuc`, not `cmder`.

```
"conemuc": "C:\\Users\\'some personal path name here\\cmder\\vendor\\conemu-maximus5\\ConEmuC.exe"
```

**Comment by jayhjim88** [comment]
Hi @randy3k, thanks for above and your amazing package. After weeks of work, I got it to work. For my earlier post I did use 2 slashes, so that wasn't the cuase. It's just in copying it over to github became 1 slash for some reason. I couldn't really find solution to make it compatible with cmder or conemuc. I got Rstudio and Repl to work but not cmder or conemuc. I went with REPL because it's nice to have codes sent to sublime.

For people in the future here is what worked for me (Windows 10 x64).
**1. ctrl+shift+p => SendCode choose program => Select sublimeRepl
2. Copy below SendCode\Support**
    {//Send parts of codes!
        "keys": ["ctrl+enter"], "command": "send_code",
        "context": [
            { "key": "selector", "operator": "equal", "operand": "source" }]
	},
    {//Send file!
        "keys": ["ctrl+alt+shift+s"], "command": "send_code",
        "args": {"cmd": "source(\"$file\")"},
        "context": [
            {"key":"selector","operator":"equal","operand":"source"}]
    },
    {//Set working directory
        "keys": ["ctrl+alt+shift+w"], "command": "send_code",
        "args": {"cmd": "setwd(\"$file_path\")"},
        "context": [
            {"key":"selector","operator":"equal","operand":"source"}]
    }

**Comment by randy3k** [comment]
Oh, please note that it should be the path to ConEmuC.exe, not ConEmu.exe. The former is located under the `conemu-maximus5/ConEmu` folder
