### ISSUE TITLE
windows version not working 

### ISSUE THREAD

**Issue by christacaggiano** [randy3k/SendCode#46]
Hi, 

I have installed sendCode as recommended in the code and in the issues. I have selected cmder to be my REPL program and added ConEmu to my command line. However, on my windows machine/sublime text3 setup, nothing happens when I execute using cmd+enter. Is there another step that I am missing? 

Thanks!

**Comment by randy3k** [comment]
You may need to put the path to ConEmuC.exe into your windows environment variable PATH.

**Comment by christacaggiano** [comment]
Yes I added it to my PATH before. I was getting an error on the sublime text console before about not finding ConEmuC.exe, since i added it to the PATH and updated my settings I am no longer getting this error, however, the package is still not working. There aren't any errors displaying on the command line to give me a hint. Have you run into this before?

**Comment by randy3k** [comment]
Just to make sure you are using `ctrl+enter`. Also, what syntax are you working on?

**Comment by christacaggiano** [comment]
Yes, ctrl+enter :)  I'm using python syntax. For specifying the path to conemuc should it be with windows backslashes (as in "\\C:\\Program Files\\ConEmu\\ConEmu\\ConEmuC.exe") 

Thanks! 
Christa

**Comment by randy3k** [comment]
it should be "C:\\Program Files\\ConEmu\\ConEmu\\ConEmuC.exe"

**Comment by christacaggiano** [comment]
WOW I AM DUMB thank you for your time and effort

**Comment by randy3k** [comment]
Great.
