### ISSUE TITLE
Gnome-Terminal and other target options

### ISSUE THREAD

**Issue by nreith** [randy3k/SendCode#47]
I am wondering if it is possible to offer any other linux options aside from screen and tmux. Gnome-terminal would be ideal and probably the most common option. The reason I prefer this, is because it better replicates the workflow on Mac OS X using Terminal or iTerm, where I ssh to a linux server and use tmux on the server. Having to use tmux both locally and on the server causes some issues with shortcuts and nesting that is unpleasant. And there is a serious necessity to use tmux on the server end, because it keeps my scripts going even if I get logged out.

The link below shows how gedit plugins accomplish this, so I wonder if it could help.

https://askubuntu.com/questions/327869/how-to-send-current-of-line-of-code-to-terminal-input-in-gedit-2013

**Comment by randy3k** [comment]
I have tried to play with gnome-terminal for a some time

**Comment by randy3k** [comment]
I have added back support of `gnome-terminal` at the latest master branch. I welcome any feedbacks.

**Comment by randy3k** [comment]
also added Pantheon-terminal
