### ISSUE TITLE
ConEmuC not found

### ISSUE THREAD

**Issue by kellijohnson** [randy3k/SendCode#49]
I am getting the following error in the sublime text 3 console with the latest update to the send code package:

reloading settings Packages/User/SendCode.sublime-settings
Package Control: No updated packages
Traceback (most recent call last):
  File "C:\~\Sublime Text 3\sublime_plugin.py", line 780, in run_
    return self.run(**args)
  File "settings in C:\~\Sublime Text 3\Packages\Default.sublime-package", line 101, in run
AttributeError: 'NoneType' object has no attribute 'replace'
ConEmuC.exe not found. Specify the path to ConEmuC.exe in SendCode.sublime-settings.

Prior to edits made within the last week everything was working on my Windows machine. I am not very familiar with sublime text packages, so please let me know what additional information I can give you.

**Comment by randy3k** [comment]
what program do you want to send code to?

**Comment by kellijohnson** [comment]
I was sending to R, but I am also fine with sending to the terminal and just running R inside there. It does not matter, but I don't have ConEmuC.exe installed on my Windows machine.

**Comment by randy3k** [comment]
You should choose R using `SendCode: Choose Program`.

**Comment by kellijohnson** [comment]
Thank you, and I am so sorry that I bugged you with something so trivial. Thank you for your quick response.
