### ISSUE TITLE
Delay when sending code to SublimeREPL in Sublime 3

### ISSUE THREAD

**Issue by LouisAsh** [randy3k/SendCode#51]
Whenever I tried to send code to SublimeREPL either for R or for Python, it seemed to simply not work. However, I suddenly realized that if I select a piece of code (line or whole file) and keep holding Ctrl+Enter for a second or so, it them almost always sends the code along (even if, quite often, it then sends it more than once).

Is there a way to solve that? If it helps to know, I am working under Windows 10 64bits, Most recent R version and Python 2.7.

**Comment by randy3k** [comment]
It is an issue of SublimeREPL. Note that SublimeREPL is quite buggy, I don't really recommend it.

**Comment by LouisAsh** [comment]
Dear Randy, thanks for your quick reply. I am indeed ready to drop SublimeREPL. The problem is that SendCode does not work well for sending big chunks of Python code to an open python session in Cmdr or ConEmu in Windows. But I guess I should open a new issue about that. I'll do it right away.

**Comment by randy3k** [comment]
Are you using ipython?
