### ISSUE TITLE
Sending multiline Python code to an open python session in Cmder

### ISSUE THREAD

**Issue by LouisAsh** [randy3k/SendCode#52]
So, in order to fully stop using the buggy SublimeREPL, here is what I am trying to accomplish. I open either an R.exe or a python.exe session in Cmder, under Windows 10 64bits. Then I try sending code to them with Sublime SendCode, both sending lines, small selections or whole selected files.

It works perfectly for R: anything that I try to send to the open R.exe session in Cmder works smoothly as it would in Rstudio or elsewhere. However, it does not work well when I try sending multi-line code to an open Python.exe session (much less an entire file). I get all sort of errors, seemingly triggered by the error:

    %cpaste -q
    File "<stdin>", line 1
    %cpaste -q
    ^
SyntaxError: invalid syntax

Is there a way around that or could you look into that? Being able to directly send code to an open python session via Cmder or other terminal/console utility would make integration and customization way smoother, besides allowing an easy way to use SendCode + Cmder to behave like Spyder or other Python IDEs.

**Comment by randy3k** [comment]
You should use iPython instead (version 5.0 or above). The vanilla python has very limited support of indentations.

By the way, did you turn of bracketed paste mode? You should have it turned on.

**Comment by LouisAsh** [comment]
Yeap, I had bracketed paste mode turned on. But you were right, using iPython did solve the initial problem. The main issue, though, is that when sending the code of a whole file (e.g. around 1000 lines) to an iPython session in Cmder, the transfer to Cmder and subsequent execution both become rather slow. For big files, it comes to the point of becoming impractical. Is there a known way around that?

If there is, then sure iPython is the way to go for this integration.

**Comment by randy3k** [comment]
Unfortunately, it is an issue of Cmder, it seems there is no better solution for Windows users now. Unless there is a better terminal emulator (may be https://hyper.is?), my best advice is to stick with Cmder.

By the way, if you really need to send over 1000 lines to the console, I would argue that it is a wrong use of SendCode. You may want to factor those 1000 lines into a file and do `ctrl+b` and `IPython -Source File` to execute the whole file.
