### ISSUE TITLE
specified program as cmder, but instantly opens and closes cmd window

### ISSUE THREAD

**Issue by rosschu** [randy3k/SendCode#55]
Sorry if the answer to this question is trivial- I'm relatively still new to programming. I'm currently using sublime on a windows machine, and I've adjusted the following settings to use SendCode with cmder:

```
"prog": "cmder",
"conemuc": "C:\\ProgramData\\cmder\\vendor\\conemu-maximus5\\ConEmu\\ConEmuC.exe"
```

However, when pressing control+enter, a new command prompt window instantly opens and instantly closes, but other than that I don't really see anything else happening. What I had in mind was for sublime to send the line of code a currently opened cmder window by pressing ctrl+enter, and see the results of sending this line in the cmder window.

Am I doing something wrong, and is there a way to fix this? Thanks for your help!

**Comment by randy3k** [comment]
Would you verify that the execrable `"C:\\ProgramData\\cmder\\vendor\\conemu-maximus5\\ConEmu\\ConEmuC.exe"` exists.

>  What I had in mind was for sublime to send the line of code a currently opened cmder window by pressing ctrl+enter, and see the results of sending this line in the cmder window.

This is the right expectation. It should send the code to a currently opened window.

**Comment by rosschu** [comment]
Hi Randy, 

Thanks for the quick reply. And yes, I just verified that the .exe file exists. Also, I checked that the ctrl+enter key binding wasn't interfering with key bindings for other packages.

**Comment by rosschu** [comment]
Hi Randy, 

Do you have any follow-ups on this issue? Thanks for your help!

**Comment by randy3k** [comment]
May be trying to reinstall Cmder? I really have no clues why it happens.

**Comment by rosschu** [comment]
Some update on the issue: this problem seems to be occurring depending on the extension of the file. 

I tried copy pasting the exact same code on multiple files, saving them with the following file extensions: .c, .js, .rb, .sh, .json, .py, .r, .do, .tex, and .txt

SendCode works fine with these extensions: .c, .js, .rb, .sh, .json, .py, .r
SendCode does NOT work with these extensions: .do, .tex, .txt

Is there reason why the package works with certain file extensions but not others?

**Comment by randy3k** [comment]
It only works with source files in default, check the keymap file for details.

PS: why you are sending text from a .txt file to shell?

**Comment by rosschu** [comment]
I figured it out. I made a stupid mistake of not double-checking keybind clashes lolol

sorry for all the trouble!
