### ISSUE TITLE
Usage: Block expansion

### ISSUE THREAD

**Issue by pjc42** [randy3k/SendCode#56]
The readme section on Block Expansion seems to imply or say that fenced blocks in Rmd files are supported:
> Markdown fenced code blocks of Markdown Extended and R Markdown are also supported.

How do I do actually that?

`ctrl+enter` just sends the current line or the current block if at beginning of a function/statement or `{}` block. 

Can I send the entire fenced block, i.e. everything in:  ` ```{r } ... r-code ... ``` `  ?

**Comment by randy3k** [comment]
Place your cursor at the ```{r} line and `ctrl+enter` should send the whole block to the console.

**Comment by pjc42** [comment]
thank you, perfect

is there a way to move between fenced blocks, i.e. from one ```{r } ... r-code ... ``` to the next?

**Comment by randy3k** [comment]
It may be out of the abilities of SendCode. It could be a feature request for R-Box.

**Comment by pjc42** [comment]
yes, that makes sense, I'll add something to R-Box as a reminder. would be awesome
