### ISSUE TITLE
Causes Sublime Text to Crash When Sending to Terminal View

### ISSUE THREAD

**Issue by Microbiology** [randy3k/SendCode#59]
First of all, thanks for making this awesome application! :)

I have been trying to use SendCode with [TerminalView](https://github.com/Wramberg/TerminalView) and have been running into some issues. I have started running R through a standard bash TerminalView window and am trying to send R code lines over to it from another R script Sublime window (I'm also using [R-Box](https://github.com/randy3k/R-Box) with it). It works fine when it is just a couple of R lines, but the code sending freezes and causes Sublime to hang/crash if I try to send more than about a hundred lines at a time (like when I try to send a larger code chunk).

Is this a know issue when trying to send a fairly large number of lines? Is there a fix for it?

Thanks for your insight and help! :)

**Comment by randy3k** [comment]
I guess you shouldn't send a large chunk of code in the first place. Try to factor out the code and save it into a file and `source(..)` it.

With that said, there are actually some solutions,

- if you install R from source (like from homebrew), it would support bracketed paste mode.
   You can then switch on the corresponding settings in SendCode to send code in the paste mode.

- Or you could try using [rice](https://github.com/randy3k/rice) which supports brackted paste mode. (And you again need to switch on the paste mode from SendCode settings)

**Comment by Microbiology** [comment]
Thanks @randy3k! Yeah it's not ideal sending that much code at a time but I have run into instances where it made my life easier so I figured I would explore it's feasibility. :D

So the bracketed paste mode did the trick! Thanks so much!

**Comment by randy3k** [comment]
Just to remind you that if you install R from the official binary, the cooresponding R does not support bracketed paste mode. It needs to be compiled with readline 7.0. And homebrew/linuxbrew R does have readline 7.0.

**Comment by Microbiology** [comment]
Cool thanks! Yeah I recently started going with rice, but I think I will also go with home-brew R over the official R if I need that.

Thanks so much for your help! 😸
