### ISSUE TITLE
when caret is positioned at the end of command in r code

### ISSUE THREAD

**Issue by faridcher** [randy3k/SendCode#61]
In the following image, the caret is placed at the end of a command. Is there a way to "send" the whole command to R console when we press <kbd>ctrl+enter</kbd> (like rstudio)? right now, it only sends the last line.

![image](https://user-images.githubusercontent.com/9982519/30652988-17adbf50-9e3f-11e7-9173-9d42d8b3645e.png)

**Comment by randy3k** [comment]
it is definitely a nice feature to have.

**Comment by randy3k** [comment]
739640d closes it.

**Comment by faridcher** [comment]
Excellent! I upgrade through package control but don't see the effect?!

**Comment by randy3k** [comment]
You'll need to install the SendCode from source (if you know how to `git clone`) or wait for a new release. I plan to tag a new release in one or two days.

**Comment by faridcher** [comment]
i installed the github (dev) version but I don't experience the effect!

**Comment by randy3k** [comment]
How did you install the github version? You might need to restart Sublime Text after installing a new package.

Also, there was a bug earlier and it may affact the result.

**Comment by faridcher** [comment]
Could you please try the following on your system? For me, 

move_rsf$encamped <- move[c('ch1','leo')] %>%
  lapply(function(xx){
  xx %>%
    subset(mode_null=="Resting") %>%
    st_geometry %>%
    rsf_ready(n_sample = length(.) * 2) %>%
    spatial_covariates(rstrs,shps)
})

the connection between `lapply(function(xx){` and `xx %>%` line is not established!

**Comment by randy3k** [comment]
I think that it is reasonable in the first case that the block is not expanded because 
```r
  xx %>%
    subset(mode_null=="Resting") %>%
    st_geometry %>%
    rsf_ready(n_sample = length(.) * 2) %>%
    spatial_covariates(rstrs,shps)
```
is a valid R syntax.

The second case is a bit complicated.... I don't think there is an easy fix. SendCode now expands upward based on operators and expands downward based on brackets and operators.

**Comment by faridcher** [comment]
that's fine. I am suggesting this and other enhancements. Code them once you got the time and energy. I might also contribute once I am done with a project.
