### ISSUE TITLE
move cursor to next/previous cell

### ISSUE THREAD

**Issue by bitworm** [randy3k/SendCode#62]
Hi Randy,

Very nice package, I use it daily.  One feature that I find very useful is a key-binding to move to the previous/next cell (without execution).  Any interest in adding this feature?

**Comment by randy3k** [comment]
what do you mean when you say a cell?

By the way, I have this in my user keymap for jump between paragraphs.
```
    // movement
    {
        "keys": ["alt+up"], "command": "move",
        "args": {"by": "stops", "empty_line": true, "forward": false}
    },
    {
        "keys": ["alt+down"], "command": "move",
        "args": {"by": "stops", "empty_line": true, "forward": true}
    },
```

**Comment by bitworm** [comment]
cell -> blocks; this code is (very close) to what I'm looking for, thank you.  Is there a way to make the cursor jump directly/only to instances of `# %%` ?  Currently my cursor moves to each empty space as well.
