### ISSUE TITLE
indentation error when code is sent to a server in an EC2 instance

### ISSUE THREAD

**Issue by Akilesh1989** [randy3k/SendCode#63]
Hi,
Thank you for this awesome package. 
I am mac user and I have sublime text3 V3.0 with SendCode installed and started using it very recently. I primarily use it for python code.

I have this issue where when I select multiple lines and hit `cmd+enter` it works on a local python shell but throws an indentation error in a python shell within an EC2 instance.

Error in the python shell within an EC2 instance,
```
>>> 0~def sample_function():
  File "<stdin>", line 1
    0~def sample_function():
     ^
SyntaxError: invalid syntax
>>>     print("hello world!")1~
  File "<stdin>", line 1
    print("hello world!")1~
    ^
IndentationError: unexpected indent
>>>
```

I am able to send a single line though,
```
>>> print("hello world!")
hello world!
```

This is my user settings in Sublime
```
{
    "prog": "terminal.app",
    "prog": "iTerm",
    "auto_expand_line": true,
    "auto_advance" : true,
    "auto_advance_non_empty": false,
    "bracketed_paste_mode": false,

    "r" : {
        "prog": "terminal"
    },

    "python" : {
        "prog": "terminal.app",
        "prog":"iTerm",
        // ipython is assumed when `bracketed_paste_mode `is false,
        "bracketed_paste_mode": true
    },

    "julia" : {
        "prog": "terminal",
        "bracketed_paste_mode": true
    },

    // path related settings

    // path to tmux
    // "tmux": "tmux",

    // path to screen
    "screen": "screen"
}
```
Can you help with this, please?

Thanks

**Comment by randy3k** [comment]
Please make sure that you are using IPython or any python console which supports bracketed paste mode.

**Comment by randy3k** [comment]
Close due to inactivity.
