### ISSUE TITLE
sendcode rstudio keybinding issue

### ISSUE THREAD

**Issue by faridcher** [randy3k/SendCode#65]
I have bounded `Load Package` command to a key. The menu item sends the code to rstudio console but the key (ctrl+shift+l) doesn't. 

```
 r_box_package_send_code {"cmd": "devtools::load_all(\"$folder\")"}
```

**Comment by randy3k** [comment]
RStudio support on windows is really tricky, I am aware of such a problem. Basically, we can only send control key to RStudio but not other keys. (It is because SendCode needs to do `ctrl+v` to paste code to RStudio.) For example, you could define the mapping `ctrl + l` but not `ctrl+shift+I`.

**Comment by randy3k** [comment]
Just found a trick 19b98ef  to hack this. See if the latest master your issue.

**Comment by faridcher** [comment]
works!
