### ISSUE TITLE
a new variable for multi package development

### ISSUE THREAD

**Issue by faridcher** [randy3k/SendCode#66]
Right now, we have the following variables that could be used in `cmd` field:

$file, the full path to the file
$file_path, the directory contains the file
$file_name, the file name
$file_basename, the file name without extension
$file_extension, the file extension
$folder, the first folder of current window
$project_path, the directory where sublime-project is stored
$selection, the text selected, or the word under cursor
$line, the current line number

In my sublime project, I have multiple R packages (folders) added to it. A new variable that detects  the package folder of current active file is a great way to do multi packages development. The folder of the package can be determined by comparing the $file_path of the active file and the sublime project folders and match the relevant folder (lets call it $file_project_path). Then one can send this path to `devtools` functions. I find myself moving the folders to top a lot.

thanks

**Comment by randy3k** [comment]
done a667f80eb691a48114cfe88dfc4cb0341e0d58c5

**Comment by randy3k** [comment]
You should be able to use it to bind new keymaps. I will update R-Box menu once a new SendCode release is up.
