### ISSUE TITLE
sendcode broken with new iterm applescript interface

### ISSUE THREAD

**Issue by bitworm** [randy3k/SendCode#68]
Sendcode seems to have broken.  Within a python script in ST3, using cmd+enter moves the  cursor to the end of the block `# %%`, as expected, but said text is not sent to my ipython session in iterm2.  Sending highlighted code also appears broken.  This may (?) have occured as a result of upgrading to High Sierra (10.13).

sendcode settings:
```
{
	"prog": "iterm",
	"python":
	{
		"bracketed_paste_mode": true,
		"prog": "iterm"
	}
}
```
and the default sublime-keymap
```
[
    {
      "keys": ["super+enter"], "command": "send_code",
      "context": [
          { "key": "selector", "operator": "equal", "operand": "source" }
      ]
   }
]
```

Any thoughts or suggestions welcome..

**Comment by randy3k** [comment]
Is there any error in the console?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bitworm** [comment]
```
File "/Users/user/Library/Application Support/Sublime Text 3/Packages/SendCode/send_code.py", line 88, in <lambda>
    sublime.set_timeout_async(lambda: sender.send_text(cmd))
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/SendCode/code_sender/sender.py", line 93, in send_text
    self.send_to_iterm(cmd)
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/SendCode/code_sender/sender.py", line 160, in send_to_iterm
    send_to_iterm(cmd, bracketed=True)
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/SendCode/code_sender/iterm/__init__.py", line 10, in send_to_iterm
    osascript(ITERM_BRACKETED, cmd)
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/SendCode/code_sender/applescript.py", line 5, in osascript
    subprocess.check_call(["osascript"] + list(args))
  File "./python3.3/subprocess.py", line 547, in check_call
subprocess.CalledProcessError: Command '['osascript', '/Users/user/Library/Application Support/Sublime Text 3/Packages/SendCode/code_sender/iterm/iterm_bracketed.applescript', '# %%\ntest code']' returned non-zero exit status 1
```

**Comment by randy3k** [comment]
It looks like your iTerm doesn't accept applescript anymore.

**Comment by bitworm** [comment]
apparently the new version of iterm2 revised their applescript interface, that they mention is not backward compatible, as seen here: https://www.iterm2.com/documentation-scripting.html.

**Comment by randy3k** [comment]
SendCode is using the new interface of iTerm2, I guess there might be some permission issues in utilizing Apple Script on the new OS.

**Comment by bitworm** [comment]
hm, ok.  If it is due to High Sierra, when/do you intend to patch this?  Thank you.

**Comment by randy3k** [comment]
I don't think it's an issue of SendCode, but an issue of your is settings. Could you try if AppleScript of iTerm2 is working?

**Comment by bitworm** [comment]
I can send text to iterm2 okay with this applescript:
`tell application "iTerm-2"
	tell current session of current window
		write text "echo 'verifying applescript can talk to iterm2'"
	end tell
end tell`

**Comment by randy3k** [comment]
I have also updated to high sierra and SendCode is just working fine with iTerm2.

**Comment by bitworm** [comment]
Thank you for the follow up.

It does indeed appear to be an issue with Iterm-2.  After selecting`install shell integration` from the iterm2 menu bar, `sendcode` started working again.  Maybe this was disabled with an iterm2 or High Sierra update, but it's no longer an issue.  Thank you for helping to debug this and maintenance of this code!

**Comment by randy3k** [comment]
It shouldn't be related to `install shell integration`, but I'm glad that it is working again for you.
