### ISSUE TITLE
Config SendCode to use REPL 

### ISSUE THREAD

**Issue by ThoDuyNguyen** [randy3k/SendCode#70]
My setup works fine with RStudio desktop version but could not with REPL R (REPL R works fine)

SOF's answer also does not work:
https://stackoverflow.com/questions/35067863/initializing-r-box-to-send-code-to-repl

My sublime text has R-Box work perfectly. 

Thank you in advance

**Comment by randy3k** [comment]
Do you mean that R is running on REPL and SendCode doesn't send code to it?

Did you change the program by using `SendCode: Choose Program`?

**Comment by randy3k** [comment]
Close due to inactivity.
