### ISSUE TITLE
Send code in roxygen examples with `#' @examples`

### ISSUE THREAD

**Issue by sckott** [randy3k/SendCode#73]
Using SendCode `v0.3.13` - setup to send to iTerm, on OSX 

It looks like https://github.com/randy3k/SendCode/blob/master/code_getter/getter.py#L147 sendcode supports sending code that is like

```r
#' 4 + 4
```

but it's not working for me with SendCode default settings at least. Maybe there is a setting I can toggle for this to work?

**Comment by randy3k** [comment]
That's knitr spin format.

```
#+ a section
a <- 1
b <- 2

#+ another section
foo <- 2
bar <- 4

**Comment by sckott** [comment]
Okay, so in the code `re.match(r"#'|#\+", view.substr(line))` what is the `#'` for?

**Comment by randy3k** [comment]
That is to break markdown syntax in between.

```
#+ a section
a <- 1
b <- 2

#' Some texts here.

#+ another section
a <- 1
b <- 2
```

**Comment by sckott** [comment]
ah okay. thx. 

Any chance of supporting sending code prefixed with `#'` ?

e.g., RStudio IDE can do it. not sure how they do it.

**Comment by randy3k** [comment]
As far as I know, RStudio sends the `#'` code as comment which SendCode also does.

**Comment by sckott** [comment]
i don't know if it's by default or not, but if rstudio IDE finds an `@examples` oxygen directive, it then sends any lines below that directive as code to it's console, e.g, 

```r
#' foobar 
#' 
#' @examples
#' foobar(4)
#' foobar(10)
foobar <- function(x) x ^ 2 
```

Any chance of SendCode doing the same?

**Comment by randy3k** [comment]
I see. RStudio does handle `#' @examples` differently.

**Comment by sckott** [comment]
It would be helpful as a developer to work on examples for documentation in R packages

**Comment by nbenn** [comment]
I just wanted to open an issue with the same request. So +1 for this from my side.

This might sound a bit hacky, but if it makes things easier, I'd be happy if any line starting with `#'` was treated as executable code (ignoring the `@examples` tag).

To me it seems more convenient to deal with the occasional parser error whenever I accidentally send a line of docs text, than to copy/paste examples between Sublime and the terminal.

**Comment by randy3k** [comment]
I finally found some time to add this support. Check the version 0.4.6. It may take package control a while to load the update.

**Comment by nbenn** [comment]
Thanks for your quick response and for the effort that goes into improving R development with Sublime.
