### ISSUE TITLE
Blocks of code encapsulated in "~0 .... 1~"

### ISSUE THREAD

**Issue by kuchenrolle** [randy3k/SendCode#77]
When I use sendtext to send to a tmux window, it works fine as long as I send individual lines, but when I try to send a function or some block of code, the code is sent to the terminal encapsulated by a leading "\~0" and a trailing "1~", so

```
def fun(arg):
  print(arg)
```

arrives at the terminal as

```
~0def fun(arg):
  print(arg)1~
```

This problem occurs for R and for python. The only sublime key binding I changed is for ctrl+#, to comment out lines. The other packages I have installed are Anaconda, Git, GitGutter, Markdown Extended, SFTP, SublimeLinter-pep8, SublimeLinter-pyflakes, SublimeREPL and Terminal.

**Comment by randy3k** [comment]
Are you not using IPython?

**Comment by kuchenrolle** [comment]
No, I'm not.

**Comment by randy3k** [comment]
You should use iPython as the native python console doesn't support bracket paste mode.

**Comment by kuchenrolle** [comment]
Okay, using iPython solved the problem for python, but what about R?

**Comment by randy3k** [comment]
Did you turn on bracketed paste mode for R syntax in the setting? The built in R console doesn’t support BPM. So either turn it off or try another R console such as [rice](https://github.com/randy3k/rice).

**Comment by kuchenrolle** [comment]
It seems to be turned-on by default, so turning it off in the settings solved the problem. Thank you!

**Comment by randy3k** [comment]
That's odd. The default should be `false` https://github.com/randy3k/SendCode/blob/0a2281798242f2a3999549e127a59a365f1d9f36/SendCode%20(Linux).sublime-settings#L6

Maybe you have changed it accidentally.

**Comment by kuchenrolle** [comment]
I have not. It also says false for me, but somehow it would send it in bracketed mode anyway and it only stopped when I added it to the user specific settings for R. Today, though, when I remove that line from the user settings for R, it still works. Random.
