### ISSUE TITLE
send code based on a marked region?

### ISSUE THREAD

**Issue by james-cunningham** [randy3k/SendCode#81]
I'm rather new to Sublime Text. As I come from Emacs I've been using Emacs Pro Essentials, and primarily acting in regions of text by marking rather than selecting them. Is there some way to send code via a marked region as opposed to manually selecting it? Or perhaps there's some way to hack it up myself, though I'm still unfamiliar with scripting Sublime Text.

Thanks a lot! It's great software and I appreciate you making it available.

**Comment by randy3k** [comment]
What kind of region you have in mind? SendCode automatically detects braces and function calls when it is triggered.

**Comment by james-cunningham** [comment]
So I'm new enough to both Sublime Text and SendCode that I may be getting my terminology incorrect, sorry. What I mean to say is that I can put my cursor somewhere, mark it with the Emacs binding ctrl+space (ctrl+k I think is the default?), move my cursor somewhere else, and then e.g. copy/cut/paste the implied region. I'm wondering if there's some way to use SendCode for a region delimited in that way.

**Comment by randy3k** [comment]
SendCode doesn't bookmark. Perhaps you could use a bookmark package to select a region and then utilize SendCode?

**Comment by james-cunningham** [comment]
I think I've wasted your time a little bit, sorry: some investigation reveals that the marking I'm describing seems to be an Emacs Pro Essentials feature (in Sublime). But I've been able to get a keyboard shortcut working that does what I want.

Thanks!
