### ISSUE TITLE
Problem sending multi-line vector/list/df assignments in R and Rmarkdown

### ISSUE THREAD

**Issue by chadbdot** [randy3k/SendCode#82]
Hi there. 

If a vector/list/dataframe assignment is broken into multiple lines (for style/readability), SendCode only recognizes the first line when sending the block (i.e., no content selected, cursor on either line). For example:

```
x <- c("a vector", "with several elements", "that needs to be", "broken into",
  "multiple lines", "will not work")
``` 
Selecting and sending the whole thing works fine. But if such a multi-line assignment is in an R code block within an Rmd file, sending that block to R produces errors. 

An easy workaround is to simply not break this kind of code into multiple lines. But it would be great if SendCode could recognize these blocks in the same way that it recognizes blocks separated by operators or pipes.

**Comment by randy3k** [comment]
Thanks for the feature request. Ya, I agree that it would be handy.

**Comment by chadbdot** [comment]
Thanks! Just tested, and it works great for regular R code. But when an assignment like the one above appears in a fenced code block in an Rmd file, sending the whole block still throws errors. 

It looks like this is a problem with any code block containing multiple lines of code within parentheses. For a slightly different (and insanely dumb) example, take the following block:

````r

```r
mtcars %>%
  mutate(
    mpg = FALSE,
    cyl = TRUE
  )
```

````

When the cursor is anywhere inside the block, the whole command is sent just fine. But if I send the _block_ (i.e. placing the cursor at the beginning of the ` ```r ` line), it appears to send each line separately, resulting in multiple errors.

**Comment by randy3k** [comment]
For rmarkdown, you may want to also turn on bracketed_paste_mode

```
    "rmd" : {
        "bracketed_paste_mode": true
    },

```

**Comment by chadbdot** [comment]
Oh right. I really should have thought of that. Works perfectly now. Thanks!

**Comment by randy3k** [comment]
Awesome.
