### ISSUE TITLE
ggplot not showing

### ISSUE THREAD

**Issue by Zoher15** [randy3k/SendCode#83]
Hey Randy,

When I run ggplot() from command line it opens up a new R graphics windows, running through sublime nothing opens up.

Also is there a way to build selective lines of code?

GREAT WORK!

best,
Zoher

**Comment by randy3k** [comment]
Would you mind telling me how to reproduce the issue?

**Comment by Zoher15** [comment]
![image](https://user-images.githubusercontent.com/29090730/35832342-f873f492-0a9a-11e8-897e-cf7d1713698b.png)
![image](https://user-images.githubusercontent.com/29090730/35832389-20a7b958-0a9b-11e8-9332-dbd497465f48.png)

**Comment by randy3k** [comment]
It seems that you are not running R in an interactive session but running the script in the sublime console which should not be used in this purpose?

**Comment by Zoher15** [comment]
So I cannot use sublime for plotting graphs?

**Comment by randy3k** [comment]
Not for this purpose. Anyway, the way that you send the code to the console is not part of SendCode. I will close it now.

**Comment by Zoher15** [comment]
Could you please help me understand? I would like to plot graphs through sublime text. What do I need to do?

**Comment by randy3k** [comment]
You would need to use an external program, e.g. RGui or Cmder.

**Comment by Zoher15** [comment]
So could I use sendcode for this?

**Comment by randy3k** [comment]
Yes, just select that in SendCode settings

**Comment by Zoher15** [comment]
It says rgui not supported for current syntax

**Comment by randy3k** [comment]
Did you select the syntax as R?

**Comment by Zoher15** [comment]
Yes I did. Am I missing any steps? installed r-box. installed sendcode. 
![image](https://user-images.githubusercontent.com/29090730/35839465-8df68282-0abe-11e8-92a0-018f1e9d54bd.png)
and this
![image](https://user-images.githubusercontent.com/29090730/35839491-adea3bce-0abe-11e8-82a7-9be2f01a3cc7.png)

**Comment by Zoher15** [comment]
Hey Randy,

Would really appreciate if you could help me figure this out.

best,
Zoher

**Comment by randy3k** [comment]
the value of `prog` should be `r` if you want to use the RGUI.

**Comment by Zoher15** [comment]
Still does not work. On selecting the text and hitting ctrl+enter does nothing

**Comment by randy3k** [comment]
Is there any message in the console?

**Comment by Zoher15** [comment]
No message nothing. Nothing moves. At least when I put prog:'rgui' a box was popping up

**Comment by randy3k** [comment]
Did you open R GUI?

**Comment by Zoher15** [comment]
Yes. It is just setting doing: setwd("C:\\Users\\zoya\\Desktop\\Exploratory Data Analysis S-670")
for any line that I hit ctrl+enter on

**Comment by randy3k** [comment]
Did you override the default key mappings?

**Comment by Zoher15** [comment]
![image](https://user-images.githubusercontent.com/29090730/35895755-e087a2a6-0b86-11e8-98ab-4a010dc61ce4.png)

**Comment by randy3k** [comment]
Just reset the key mappings to the default settings.

**Comment by Zoher15** [comment]
Randy. Thank you so much! I really really appreciate your patience. I apologize for the trouble and me stumbling around! :) 👍 💯 

best,
Zoher
