### ISSUE TITLE
Sending whole Rmardown code chunks to TerminalView 

### ISSUE THREAD

**Issue by kofm** [randy3k/SendCode#84]
Hello,

I'm starting to use this awesome ST Package to emulate RStudio. Is it possible to send to e.g. TerminalView a whole knitr chunk instead of a line or selected text?

Thanks!

**Comment by randy3k** [comment]
If you put the cursor at the beginning line of the chunk ```

**Comment by kofm** [comment]
Ops.. sorry for opening this stupid issue.

Thanks!

**Comment by mikedecr** [comment]
Purely out of curiosity, would you @randy3k foresee any issue with a "send whole chunk" command that would work even if the cursor is inside the chunk (i.e. not on the ``` line), by doing something like the following: 

- if the cursor is located within a fenced code block, scroll up lines until we find ` ``` `
- if we find it, stop there and run the chunk (using the infrastructure you have already built)
- if we don't find it, do nothing (i.e. previous cursor location)
