### ISSUE TITLE
retrieve code feature

### ISSUE THREAD

**Issue by bitworm** [randy3k/SendCode#85]
Hi Randy,

Have you ever considered adding a "retrieve code" function, that would send code back from a REPL to ST3?  I don't know how difficult this would be to implement, but would be a very useful feature.

**Comment by randy3k** [comment]
It is indeed very difficult and also depends on which repl is under consideration. I don’t think I will implement anything along this direction.

**Comment by bitworm** [comment]
I see.  Given that you've written sendcode, maybe you could suggest where to start to do the same from iterm to sublime?

**Comment by randy3k** [comment]
actually, I am not entirely sure what do you mean when you said send code back from a REPL to ST3. Do you want to send the text being highlighted or the command line history? If history is concerned, it will also depend on which language repl you are talking about.
