### ISSUE TITLE
Problem sending code to "konsole" on Kubuntu

### ISSUE THREAD

**Issue by svolpers** [randy3k/SendCode#87]
When sending code using "Strg+Enter", current line is duplicated instead of send to terminal. 

My user settings are as follows: 

{
	"linux_terminal": "konsole",
	"prog": "linux-terminal",
	"r":
	{
		"bracketed_paste_mode": false,
		"prog": "linux-terminal"
	}
}

Default settings with tmux work as expected.

**Comment by randy3k** [comment]
Could you run `xprop | grep WM_CLASS` and click the active terminal? It would tell you the terminal class. I believe it was because SendCode was not able to find the terminal.

**Comment by svolpers** [comment]
Thank you for the reply. Yes, I did and it returns: 
WM_CLASS(STRING) = "konsole", "konsole"

**Comment by randy3k** [comment]
Well, I may need a virtual machine to investigate.

**Comment by randy3k** [comment]
648b3e1 should have fixed it and a new tag v0.4.2 has released. The reason was because `xdotool windowfocus` doesn't work very well on KDE.

**Comment by randy3k** [comment]
It looks like konsole supports dbus. So one actually can use it to send text to konsole without xdotool. However, I am not a KDE user (in fact, I am even not a regular linux user), so I don't think I will implement it.

**Comment by svolpers** [comment]
Okay, thanks for clarification. As tmux works, it will be okay for me.
