### ISSUE TITLE
Do not send the line immediately after a commented line

### ISSUE THREAD

**Issue by kklot** [randy3k/SendCode#88]
As described, trying to send the line after the commented one will send the commented one, e.g.,
```R
#---------commented line
rnorm(100) # the cursor is here
``` 
press Cmd + Enter (Mac) will send the commented line to R (happened with different clients: Terminal View, R GUI, Terminal, and R REPL).

**Comment by randy3k** [comment]
I cannot reproduce it. Only the line `rnorm(100)` is sent on my mac machine.

**Comment by kklot** [comment]
Sorry I also cannot reproduce with the above code as well, I figured out because I have the yaml header in the file, e.g.
```R
---
title: "Baseline"
---

# -------------------------------------------------------------------------
rnorm(100) # the cursor is here
```

**Comment by randy3k** [comment]
What syntax did you choose? R markdown or R?

**Comment by kklot** [comment]
Oh right, I chose R (to avoid some R markdown keyboard shortcut conflicts) and caused the issue, thanks for the replies.

**Comment by randy3k** [comment]
I still cannot reproduce it with the R syntax...
