### ISSUE TITLE
Execute sent code blocks in IPython

### ISSUE THREAD

**Issue by jiaseny** [randy3k/SendCode#90]
I've recently upgraded IPython to 5.6.0 and I'm calling it from iTerm 2 on MacOS High Sierra.

Things work fine if I send a single line of code to iTerm 2 from Sublime Text 3. 
However, after selecting multiple lines of code in Sublime and sending it to iTerm, the cursor in iTerm would be on a newline after the sent code, but the code would not be executed unless I go to iTerm  and manually press enter or shift+enter.

![screenshot](https://user-images.githubusercontent.com/7111557/39022558-1cca3746-4404-11e8-9803-c6b68ecc9382.png)

Is there a way to automatically append an extra new line after sending multiple lines of code from Sublime? Thanks!

**Comment by randy3k** [comment]
I stupidly commented one of the lines in the latest release. It should have been fixed now.

**Comment by jiaseny** [comment]
Thanks! Should I upgrade the package somehow? I tried in Package Control, but it tells me "There are no packages ready for upgrade"...

**Comment by randy3k** [comment]
It may take a while for Package Control to cache the upgrade. Please try again later.
