### ISSUE TITLE
Feature request: Indicate code cells by comments for Julia

### ISSUE THREAD

**Issue by crstnbr** [randy3k/SendCode#95]
For Julia, a block is currently identified by  `begin` and `end` keywords. In case of Python one can use `# %%` comments to indicate blocks/code cells. I'd love to have the latter possibility for Julia as well.

I find it much cleaner to use special comments (`# %%`) for code cells. Reasons are
1. Syntax highlighting (I like code cell definitions to be less prominently colored than actual code.)
2. `begin` and `end` are keywords and as such effect the code (for example only the last statement will be returned and displayed)

I guess it should be rather easy to add `# %%` functionality for Julia.

**Comment by randy3k** [comment]
@crstnbr 

Sorry for the late (after a month) reply. I finally find some time to address this.
