### ISSUE TITLE
code not sending on ubuntu 14.04

### ISSUE THREAD

**Issue by bitworm** [randy3k/SendCode#96]
Hi Randy,

I have set up a new machine on ubuntu with Sublime and python on the default (gnome) terminal.  Instead of sending the code, it sends `^M` or nothing at all to ipython 6.x.  A new (blank) line is appended in ipython, indicating that sendcode is talking to it; just not sending the  code.  Any suggestions?  Here are the settings:

```
{
	"prog": "linux-terminal",
	"python":
	{
		"bracketed_paste_mode": true,
		"prog": "linux-terminal"
	}
}
```
(key bindings file is empty)

Thank you

**Comment by randy3k** [comment]
I have no idea on top of my head. FYI, `^M` does represent the enter key.

**Comment by bitworm** [comment]
Actually, I'm the terminal program I'm using is in **unity**, and I suspect this may be the problem.  Can you suggest how to debug?  Where are the error logs to see what's failing?

FWIW, sending to a screen session works, so it appears to be an issue handing off to the terminal.

Thank you.

**Comment by randy3k** [comment]
It should work with unity. At least when last time I checked it with Ubuntu 14. Does `ctrl+shift+v` pastes to the terminal?

You could try to play the different sleep duration between the calls in [`send_to_linux_terminal`](https://github.com/randy3k/SendCode/blob/cab3cf5638933c309d08cd581cd35963bf13cc38/code_sender/linux/__init__.py#L11-L43)

**Comment by bitworm** [comment]
This worked!  I had remapped to `ctrl+v`.  I didn't realize this would break sendcode.  Thank you.

**Comment by randy3k** [comment]
Then how you issue a sigint?

**Comment by bitworm** [comment]
this was overlooked, as I was just setting up a new machine (and am new to ubuntu)
