### ISSUE TITLE
Issue sending to ipython in windows terminus panel

### ISSUE THREAD

**Issue by gabevar** [randy3k/SendCode#99]
I'm using this setup: latest version of SublimeText 3, running SendCode with bracketed paste mode on, outputting to a terminus panel running ipython.

I'm running into two issues:

1) When sending one line of code, the text will paste into terminus but then require me to hit enter in the terminal or send a blank line of code via SendCode in order to run.

2) When sending multiple lines of code, the text will copy correctly and run immediately. However it will append [~200 at the start of the code, and end the last line with [~201. This triggers a SyntaxError.

Any advice is much appreciated ! Let me know if any other information can be useful.

**Comment by gabevar** [comment]
Thank you for the quick response,

I am running i python 6.5.0. Do you recommend a previous version for
compatibility with SendCode?

Gabriel Varela

**Comment by randy3k** [comment]
6.5.0 is fine, what os is it?

**Comment by randy3k** [comment]
I see that fro the title. Ipython does not support bracketed paste mode on Windows. Let me see if I can do anything.

**Comment by gabevar** [comment]
Much appreciate, let me know if I can be of any more help !

Gabriel Varela

**Comment by randy3k** [comment]
It should be now fixed.

**Comment by gabevar** [comment]
Hi Randy,

Tested and works perfectly. Thank you for your hard work and useful tools.

Gabriel Varela

**Comment by williamszk** [comment]
I'm using windows, ipython 7.8.0  on terminus:
1. Sending one line of code, the code is not automatically executed so I need to manually press enter. And there are two extra lines after the code. What appears on terminus:
![image](https://user-images.githubusercontent.com/50533840/68361070-3391a700-0101-11ea-8dff-53cd8ae18d71.png)
2.  When sending a block of code the code is not executed automatically, and there is a 

> ^[

that appears after the code sent. Also there is an extra line.
The code sent:
![image](https://user-images.githubusercontent.com/50533840/68361189-b3b80c80-0101-11ea-95ae-b95b194d53b3.png)
What appears on terminus:
![image](https://user-images.githubusercontent.com/50533840/68361217-cc282700-0101-11ea-914a-aad329dea3a2.png)

**Comment by randy3k** [comment]
ipython on Windows is always tricky and the behaviour changes for every version. Let me fire up a windows VM to test.

**Comment by randy3k** [comment]
I could reproduce it with the lastest ipython.

**Comment by randy3k** [comment]
v0.4.14 should improve it. Though it still doesn't work occasionally.

**Comment by williamszk** [comment]
It is working fine now.

Thank you, Randy.
